### ISSUE TITLE
`stdout maxBuffer exceeded`

### ISSUE THREAD

**Issue by vjpr** [lerna/lerna#1104]
There are a few existing closed issues on this, but I am still seeing the error in 2.5.1.

https://github.com/lerna/lerna/issues?utf8=%E2%9C%93&q=is%3Aissue%20stdout%20maxBuffer%20is%3Aclosed%20

```
lerna info Bootstrapping 24 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute callback with error
lerna ERR! Error: stdout maxBuffer exceeded
lerna ERR!     at PassThrough.stream.on (/usr/pnpm-global/1/node_modules/.registry.npmjs.org/get-stream/3.0.0/node_modules/get-stream/index.js:30:12)
lerna ERR!     at emitOne (events.js:120:20)
lerna ERR!     at PassThrough.emit (events.js:210:7)
lerna ERR!     at addChunk (_stream_readable.js:266:12)
lerna ERR!     at readableAddChunk (_stream_readable.js:249:13)
lerna ERR!     at PassThrough.Readable.push (_stream_readable.js:211:10)
lerna ERR!     at PassThrough.Transform.push (_stream_transform.js:147:32)
lerna ERR!     at PassThrough.afterTransform (_stream_transform.js:88:10)
lerna ERR!     at PassThrough._transform (_stream_passthrough.js:42:3)
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
(node:7223) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: stdout maxBuffer exceeded
(node:7223) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.5.1 |
| `yarn --version` | 1.0.0 |
| `node --version` | 8.4.0 |

| OS | Version |
| --- | --- |
| RHEL | 5 |

**Comment by bennyn** [comment]
I am also getting this issue when running `lerna bootstrap`:

| Executable | Version |
| --- | --- |
| lerna --version | 2.5.1 |
| npm --version | 5.5.1 |
| yarn --version | 1.3.2 |
| node --version | 8.9.0 |

Here is my stack trace:

> yarn install v1.3.2
[1/4] Resolving packages...
success Already up-to-date.
$ lerna bootstrap
lerna info version 2.5.1
lerna info versioning independent
lerna info Bootstrapping 2 packages
lerna ERR! execute callback with error
lerna ERR! Error: stderr maxBuffer exceeded
lerna ERR!     at PassThrough.stream.on (/home/travis/build/wireapp/wire-web-lerna/node_modules/get-stream/index.js:30:12)
lerna ERR!     at emitOne (events.js:121:20)
lerna ERR!     at PassThrough.emit (events.js:211:7)
lerna ERR!     at addChunk (_stream_readable.js:263:12)
lerna ERR!     at readableAddChunk (_stream_readable.js:246:13)
lerna ERR!     at PassThrough.Readable.push (_stream_readable.js:208:10)
lerna ERR!     at PassThrough.Transform.push (_stream_transform.js:147:32)
lerna ERR!     at PassThrough.afterTransform (_stream_transform.js:88:10)
lerna ERR!     at PassThrough._transform (_stream_passthrough.js:42:3)
(node:3706) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: stderr maxBuffer exceeded
(node:3706) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn install --mutex network:43273 --non-interactive --exact

Is the `--max-buffer` option documented somewhere? I tried with `lerna bootstrap --max-buffer 100000000` but no luck.

For me this issue occurs when I move dependencies from my packages into the `package.json` of `lerna` (to share them). When I keep my dependencies within the packages, then I don't run into this problem.

Here is my **lerna.json**:

```json
{
  "devDependencies": {
    "lerna": "2.5.1"
  },
  "private": true,
  "scripts": {
    "clear": "lerna run clear",
    "dist": "lerna run dist",
    "bootstrap": "lerna bootstrap",
    "test": "lerna run test"
  },
  "workspaces": [
    "packages/*"
  ]
}
```

And my **package.json**:

```json
{
  "devDependencies": {
    "browser-sync": "2.18.13",
    "concurrently": "3.5.0",
    "cross-env": "5.1.1",
    "istanbul": "0.4.5",
    "jasmine": "2.8.0",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-diff-reporter": "1.1.1",
    "karma-sourcemap-loader": "0.3.7",
    "lerna": "2.5.1",
    "rimraf": "2.6.2",
    "sinon": "4.0.2",
    "sinon-har-server": "0.3.0",
    "typescript": "2.6.1",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.4"
  },
  "private": true,
  "scripts": {
    "clear": "lerna run clear",
    "dist": "lerna run dist",
    "postinstall": "lerna bootstrap",
    "test": "lerna run test"
  },
  "workspaces": [
    "packages/*"
  ]
}
```

**Comment by evocateur** [comment]
@bennyn You're using yarn workspaces, which as I understand it means you should keep the dependencies in the packages (because yarn already dedupes stuff into the root for you).

@vjpr I'm going to need an example reproduction, I can't diagnose it from the stack trace.

**Comment by vjpr** [comment]
@evocateur This will be tricky. Its happening on remote ubuntu machine with a company project.

Its an issue with `execa` when used with promises it seems to buffer stdout. See https://github.com/sindresorhus/execa/issues/84

The `maxBuffer` should be set to something large, or configurable in lerna cli/config.

Or better, that streams are used instead of promises for execa commands.

**Comment by evocateur** [comment]
I suppose we need to figure out a way to avoid wrapping certain `execa` calls with promises. Passing`--max-buffer` (or configuring `maxBuffer` in lerna.json) should have worked, but really the underlying issue is that we shouldn't be buffering a certain class of execution that we never ever want the output from.

Playing around locally, it seems pretty much any time we call `ChildProcessUtilities.exec()` the only thing that matters is potential error output...

**Comment by vjpr** [comment]
> never ever want the output from.

I assume you mean in memory...I would say that you always want the output available for logging purposes and errors.

**Comment by evocateur** [comment]
yes, I meant `stdout`, still piping `stderr` to catch any errors. These exec calls are for `npm install` and the like, whose `stdout` tends to be irrelevant.

**Comment by vjpr** [comment]
> npm install and the like, whose stdout tends to be irrelevant.

But if there are peer dep warnings and things these are useful right? Or do warning goto stderr?

**Comment by evocateur** [comment]
The only thing we log right now from `npm install`/`yarn install` is an actual error, like when it can't find a package in the registry. Otherwise the output from highly-concurrent installations becomes a mishmash of unreadable spam.

**Comment by vjpr** [comment]
> is an actual error

It think its better to show the logs/stream output that would be generated if the command was run standalone for installs.

**Comment by evocateur** [comment]
Most install output is a feverish deluge of progress bar output. How do you propose logging that when multiple concurrent install processes are running?

(spoiler: it's really not worth it)

**Comment by vjpr** [comment]
Hmm yeh concurrent installs are tricky to stream with progress bar output. But if there are non-progress bar logs they really should be shown.

Here are some ideas:

1. Allow redirecting all install logs to a file so you can `tail -f`.
2. Allow passing flags to the package managers to turn off progress bar output and set the log level.
3. Strip curses lines from the logs that are shown, and prefix each line with the directory its running in.

**Comment by bennyn** [comment]
@evocateur: Thanks for the hint! 

I put back the dependencies to their individual packages to make use of Yarn's workspaces feature. But I also noticed that I get the `maxBuffer` error when `lerna bootstrap` is executed within NPM's `postinstall` script. Therefore I created a separate script (`npm run boot`) in my **package.json** file to run `lerna bootstrap`:

```json
{
  "devDependencies": {
    "lerna": "2.5.1"
  },
  "private": true,
  "scripts": {
    "boot": "lerna bootstrap"
  },
  "workspaces": [
    "packages/*"
  ]
}
```

**Comment by evocateur** [comment]
When hoisting, either with npm or yarn workspaces, you want to avoid postinstall in the root, as it can cause cycles. With yarn, you don’t need it at all, since `yarn install` does the workspace setup immediately.

**Comment by GabeAtWork** [comment]
I'm having a related issue when using `lerna run --parallel` with scripts that run for a long time (typically, watch modes).

Under some conditions, those scripts have a very high log output. After a while, the lerna command exits with this error: 

```
lerna ERR! MaxBufferError: stdout maxBuffer exceeded
lerna ERR!     at PassThrough.stream.on (/path/to/my/code/node_modules/@lerna/child-process/node_modules/get-stream/index.js:41:19)
lerna ERR!     at emitOne (events.js:121:20)
lerna ERR!     at PassThrough.emit (events.js:211:7)
lerna ERR!     at addChunk (_stream_readable.js:263:12)
lerna ERR!     at readableAddChunk (_stream_readable.js:246:13)
lerna ERR!     at PassThrough.Readable.push (_stream_readable.js:208:10)
lerna ERR!     at PassThrough.Transform.push (_stream_transform.js:147:32)
lerna ERR!     at PassThrough.afterTransform (_stream_transform.js:88:10)
lerna ERR!     at PassThrough._transform (_stream_passthrough.js:42:3)
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
lerna ERR! lerna stdout maxBuffer exceeded
error Command failed with exit code 1.
```

I've never had this issue when launching the individual commands, even with the same high output. Having read other issues in the repo (particularly #278), I also tried the `--stream` option, but it didn't seem to work either.

As it is, those `lerna run`s get interrupted after a while.

Executable | Version
-- | --
lerna --version | ^3.4.1
npm --version | 6.4.1
yarn --version | 1.10.1
node --version | 8.12.0

OS | Version
-- | --
MacOS | 10.13.6

**Comment by GabeAtWork** [comment]
@starandtina not quite, I've simply worked around it by reducing the output of the individual commands.

I don't think the `run` command is particularly well suited to watch modes as it is now (for instance, command interruption doesn't quite work as you'd hope, see [this Stackoverflow question](https://stackoverflow.com/questions/52926315/interrupt-all-lerna-parallel-tasks-at-once)). Day to day, I mostly use `run` for build commands, and directly run watch-based dev commands for the packages I work on.

**Comment by starandtina** [comment]
I had different use case with you, @GabeAtWork. I run into this issue when I published the packages into my private registry.

![image](https://user-images.githubusercontent.com/613990/50076670-4bc4b300-021d-11e9-8b67-040fe391484b.png)

Executable | Version
-- | --
lerna --version | 3.2.1
npm --version | 6.4.1
node --version| 10.14.2

**Comment by harshil-h** [comment]
lerna ERR! MaxBufferError: stdout maxBuffer exceeded
--
lerna ERR! at PassThrough.<anonymous> (/app/node_modules/get-stream/index.js:41:19)
lerna ERR! at PassThrough.emit (events.js:327:22)
lerna ERR! at addChunk (_stream_readable.js:302:12)
erna ERR! at readableAddChunk (_stream_readable.js:274:11)
lerna ERR! at PassThrough.Readable.push (_stream_readable.js:217:10)
lerna ERR! at PassThrough.Transform.push (_stream_transform.js:152:32)
lerna ERR! at PassThrough.afterTransform (_stream_transform.js:96:10)
lerna ERR! at PassThrough._transform (_stream_passthrough.js:46:3)
lerna ERR! at PassThrough.Transform._read (_stream_transform.js:191:10)
  | 2020-05-27T20:31:45.552+05:30 | lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
  | 2020-05-27T20:31:45.552+05:30 | lerna ERR! lerna stdout maxBuffer exceeded
  | 2020-05-27T20:31:45.575+05:30 | error Command failed with exit code 1.

**Comment by AlonMiz** [comment]
running with `--max-buffer 100000000` still getting those errors frequently.
very annoying
```
lerna ERR! MaxBufferError: stdout maxBuffer exceeded
lerna ERR!     at PassThrough.stream.on (/Users/alonmiz/logzio/gaia-hermes-ws/node_modules/get-stream/index.js:41:19)
lerna ERR!     at PassThrough.emit (events.js:194:15)
lerna ERR!     at addChunk (_stream_readable.js:284:12)
lerna ERR!     at readableAddChunk (_stream_readable.js:261:13)
lerna ERR!     at PassThrough.Readable.push (_stream_readable.js:220:10)
lerna ERR!     at PassThrough.Transform.push (_stream_transform.js:151:32)
lerna ERR!     at PassThrough.afterTransform (_stream_transform.js:92:10)
lerna ERR!     at PassThrough._transform (_stream_passthrough.js:42:3)
lerna ERR!     at PassThrough.Transform._read (_stream_transform.js:190:10)
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
lerna ERR! lerna stdout maxBuffer exceeded
```

**Comment by denissabramovs** [comment]
Same here, still not fixed
```
lerna ERR! MaxBufferError: stderr maxBuffer exceeded
lerna ERR!     at PassThrough.<anonymous> (/var/local/project/node_modules/get-stream/index.js:41:19)
lerna ERR!     at PassThrough.emit (events.js:322:22)
lerna ERR!     at addChunk (_stream_readable.js:286:12)
lerna ERR!     at readableAddChunk (_stream_readable.js:264:11)
lerna ERR!     at PassThrough.Readable.push (_stream_readable.js:209:10)
lerna ERR!     at PassThrough.Transform.push (_stream_transform.js:152:32)
lerna ERR!     at PassThrough.afterTransform (_stream_transform.js:96:10)
lerna ERR!     at PassThrough._transform (_stream_passthrough.js:46:3)
lerna ERR!     at PassThrough.Transform._read (_stream_transform.js:191:10)
lerna WARN complete Waiting for 19 child processes to exit. CTRL-C to exit immediately.
lerna ERR! lerna stderr maxBuffer exceeded
error Command failed with exit code 1.
```

**Comment by jerloo** [comment]
Same here with storybook
related: https://github.com/storybookjs/storybook/issues/14342

**Comment by kg-currenxie** [comment]
Same
![Screenshot 2022-01-10 at 11 40 08](https://user-images.githubusercontent.com/48229166/148715942-71ce4b9d-af80-435b-9f6e-b8310a51c5e6.png)

**Comment by YukioDev85** [comment]
I discovered the same error.
What is the best solution?
