### ISSUE TITLE
Lerna publish fails to recognize git tags on CI

### ISSUE THREAD

**Issue by dorsharon** [lerna/lerna#1645]
Whenever I run our release flow (`lerna version && lerna publish from-git`) on our Bamboo CI, the `lerna publish` command fails to see the recently-pushed git tags of the packages to publish.

I've even printed the output of '`git log -1`' to see that it actually sees the Publish commit made by `lerna version`, yet it still fails:

```
build	02-Sep-2018 14:19:09	Date:   Sun Sep 2 14:19:07 2018 +0300
build	02-Sep-2018 14:19:09	
build	02-Sep-2018 14:19:09	    Publish
build	02-Sep-2018 14:19:09	    
build	02-Sep-2018 14:19:09	     - @chkp/build@0.3.2
build	02-Sep-2018 14:19:09	     - @chkpkit/summary-header@1.0.0
build	02-Sep-2018 14:19:09	     - @chkp/storybook@2.0.0
build	02-Sep-2018 14:19:09	Now starting publishing...
error	02-Sep-2018 14:19:10	lerna notice cli v3.2.1
error	02-Sep-2018 14:19:10	lerna info versioning independent
error	02-Sep-2018 14:19:11	lerna info require-scripts enabled
error	02-Sep-2018 14:19:11	lerna notice from-git No tagged release found
error	02-Sep-2018 14:19:11	lerna success No changed packages to publish 
```

How can I fix this?
On my local machine, lerna publish is able to work properly.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.2.1 |
| `npm --version`  | 5.8.0 |

**Comment by M3kH** [comment]
We had the same issue. We hook `git fetch --tags` before `lerna publish`.

**Comment by evocateur** [comment]
I need more context to even begin debugging. The `lerna.json` would be a good start. [This call](https://github.com/lerna/lerna/blob/37642a066ed0243d6312240c49c635c3431a989b/commands/publish/lib/get-current-tags.js#L18) retrieves the current tags, and [this one](https://github.com/lerna/lerna/blob/37642a066ed0243d6312240c49c635c3431a989b/commands/publish/lib/get-tagged-packages.js#L15) locates the changed packages from the tagged revision in non-independent ("fixed") versioning mode.

**Comment by mtford90** [comment]
I'm facing this also. I haven't delved too far into this yet and i'll report back if I solve it, but it seems like it's something to do with git setup.

`git tag --sort version:refname --points-at HEAD` returns nothing for me. 

`git tag --sort version:refname` however, works fine. So lerna probably isn't receiving any versions from git in my case.

**Comment by mtford90** [comment]
Ok so here is what went wrong and caused confusion in my case:

1. My CI build failed before the `lerna publish` command. 
2. I committed and pushed a fix for this issue.
3. Lerna looks for tags that point at `HEAD` - the current commit.
4. It finds none - the tag is on the prior commit that caused a broken CI build.

Note that this was a bug in my CI build process - NOT in the code that I was trying to push. The solution was to force publish (and hence retag) before committing & pushing again even though the code tagged was ready to be published despite the CI failure.

I don't really see this as a failure on Lerna's part - but it certainly caused a bit of confusion. I can see why Lerna wouldn't walk backwards through the git history and release tagged versions - this would mean you could end up publishing code that previously failed CI legitimately. It just means there is a bit of awkwardness involved when something goes wrong with the CI process.

**Comment by evocateur** [comment]
It's a bit confusing that you would run `lerna version` _and_ `lerna publish from-git` subsequently in the same CI build. Why not just `lerna publish`? It calls `lerna version` implicitly.

**Comment by sunaiwen** [comment]
Seems this issue still exists on `v4`.

`lerna changed` could detect the changed packages while `lerna publish` just come out with **No changed packages to publish**.

Does anyone have further imformation?

**Comment by bcdxn** [comment]
I'm having the same issue. A simplified view of our CI process looks like the following:

1. get source
2. `lerna version ...` to update tags based on conventional commits
3. linting (using `lerna run lint --since`)
4. testing (using `lerna run lint --since`)
5. run static analysis using a tool outside of our pipeline where we pass the previously created tag information as an identifier
6. assuming 2-4 pass, `lerna publish from-git`

Steps 1-4 work great but when our CI pipeline gets to the publish step I see:

> lerna notice cli v3.22.1
> lerna success No changed packages to publish

When I run `git tag --sort version:refname --points-at HEAD` I can see the tag created by the `lerna version` command. My understanding is that is was the exact use case for the `from-git` option. Am I missing something or is this a bug?

**Comment by amalitsky** [comment]
Likely this is because _lerna_ expects you to be checked out into that particular tag (commit associated with it). I.e.

```
git checkout your-tag-name
lerna publish from-git
```
