### ISSUE TITLE
Selective bootstrapping

### ISSUE THREAD

**Issue by madbence** [lerna/lerna#1847]
## Expected Behavior

given packages `a`, `b` in a monorepo where `a` depends on `b`, `lerna` should be able to bootstrap only `a`, and install `b` from the registry instead of symlinking.

## Current Behavior

```sh
$ lerna bootstrap --scope a
```

will bootstrap only `a`, but it symlinks `b`, so `a` will be broken, as dependencies of `b` are not present (because it's not bootstrapped).

```sh
$ lerna bootstrap --scope a --incude-filtered-dependencies
```

will bootstrap `a` and `b`, which is something i'd like to avoid.

```sh
$ cd packages/a
$ npm ci
```

will bail out, as `package-lock.json` is not in sync with `package.json` (`b` is missing from `package-lock.json`).

```sh
$ npm i --no-save
```

succeeds, but i'm not sure if it uses `package-lock.json`. i'm not even sure that the `package-lock.json` in the package is valid (i'd say that it isn't).

## Context

when a ci build is triggered, i don't want to bootstrap/build all the packages for every build, only the packages that have changed.

**Comment by evocateur** [comment]
Manual `npm ci` in a leaf node is pretty much incompatible with `lerna bootstrap`.

This isn't the first request for selective bootstrapping, and my negative reaction in almost every instance is based on the fact that I don't want to turn `lerna` into a mind-reading program that attempts to understand which packages are not needed to run a given module.

You're better served by optimizing your build steps (I'm assuming you have a build step, since whatever the `pkg.main` is targeting doesn't exist) than making fancy bootstraps.

**Comment by madbence** [comment]
to me it seems that `npm i --no-save` is currently the only way to do this, but my fear is that the builds won't be reproducible then, because the `package-lock.json` assumes that the monorepo dependencies will be linked.

**Comment by evocateur** [comment]
If you use relative `file:` specifiers to express the sibling dependencies(*), it locks the entire tree from the root. Still doesn't solve the underlying issue, but you'd be much more reproducible at least.

(*): Run `npx lerna link convert` once, and future bootstrapping is just `npm install` (or `npm ci`) in the root.

**Comment by madbence** [comment]
i'm using semver version specifiers to express the dependencies.

based on my current understanding, right now in order for reproducible builds (ie. installing deps based on `package-lock.json`), assuming that you're only using semver version specifiers to express your dependencies, you need to bootstrap dependencies as well (`--include-filtered-dependencies`), because in a package `a` the `package-lock.json` no longer represents the used dependencies of `a` (you also need `package-lock.json` from package `b`, etc, whatever package `a` is directly or indirectly depending on in your monorepo).

**Comment by evocateur** [comment]
The entire theme of this issue is one that has been brought up many times, and I have always responded in the negative. The desire for "partial" bootstrapping represents a code smell that you need to separate concerns better. Just to reiterate.

Be that as it may, one reason (among many) that I recommend moving away from `lerna bootstrap` is that it mangles the leaf package.json such that any lockfile created in the leaf package root will _always_ be inaccurate, as it will _always_ omit the local sibling dependencies. There's no getting around this with `lerna bootstrap`.

**Comment by madbence** [comment]
i'd like to understand what do you mean by _separation of concerns_ in this context. usually we work with this kind of structure:

![untitled diagram 2](https://user-images.githubusercontent.com/296735/50825278-f1f56b80-1338-11e9-9bc0-e84c7450e5c5.png)

all the packages and the applications are in the same monorepo. most of the time, people are working on `application a` or `application b` (usually not both). when i'm working on `application a`, i don't want to bootstrap `c`, `d`, `f`, and `g`, because they are touched infrequently, they contain only some common components, and they might take a long time to bootstrap. i also don't want to bootstrap `e` and `h`, because i never work with them (and potentially i don't even know what's their purpose).

right now, i have to either

- bootstrap all the packages _or_
- bootstrap `application a` and it's dependencies (direct or indirect)

i'd like to avoid both options, as they are too much time-consuming. as far as i know, there's no third option, i'm not sure what do you mean by _moving away from `lerna bootstrap`_. i can `npm install` in `application a`, but that'll mess up the `package-lock.json` file.

**Comment by evocateur** [comment]
The natural separation of concerns appears to be the applications. If they are truly owned by different teams altogether (or might as well be), they don't really need to be in the same monorepo.

> i'm not sure what do you mean by moving away from lerna bootstrap

As I mentioned [above](https://github.com/lerna/lerna/issues/1847#issuecomment-451312790):
> Run npx `lerna link convert` once, and future bootstrapping is just `npm install` (or `npm ci`) in the root.

**Comment by evocateur** [comment]
Yeah, this was fixed in https://github.com/lerna/lerna/commit/71174e4 (released in v3.10.3), forgot to link this issue. Go hog wild.

**Comment by tiagobento** [comment]
@evocateur Hi! Sorry for posting on this old thread, but I'm still having problems with filter flags on `lerna bootstrap`. It seems that no matter what I try, all the dependencies of all packages are still fetched and placed on `node_modules`. I'm using Lerna 4.0.0 with Yarn 1.22.10 and `workspaces: true`. Thanks in advance!

**Comment by matthew-dean** [comment]
This also doesn't seem to be working for me. Limiting the `--scope` to one package (`lerna bootstrap --scope a`) still installs the dependencies of _all_ packages, regardless of scope.

This is happening with Lerna 4.0.0 and Yarn v1.22.17, despite documentation here: https://www.npmjs.com/package/@lerna/filter-options

We want to do this selective dependency installation in deploy environments, so that we're not spending a bunch of wasted time installing dependencies for apps that are not being built / deployed.

**Comment by matthew-dean** [comment]
@tiagobento I wonder if this is related to / a duplicate of: https://github.com/lerna/lerna/issues/2254
