### ISSUE TITLE
can not add local package

### ISSUE THREAD

**Issue by luponZ** [lerna/lerna#1953]
## Expected Behavior
when i run 
```bash
 lerna add module-0 --scope=module-1
```
it should link to module-1
## Current Behavior
but npm is output error message, it tell me
```log
lerna notice cli v3.13.1
lerna info filter [ 'module-1' ]
lerna info Adding module-0 in 1 package
lerna notice filter including "module-1"
lerna info filter [ 'module-1' ]
lerna WARN bootstrap Installing local packages that do not match filters from registry
lerna info Bootstrapping 1 package
lerna info Installing external dependencies
lerna ERR! npm install --no-save exited 1 in 'module-1'
lerna ERR! npm install --no-save stderr:
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for module-0
```

but when i run 
```bash
 lerna add module-0
```
 it linked others successfully

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "1.0.0"
}
```
</p></details>

<details><summary>module-0/package.json</summary><p>

```json
{
  "name": "module-0",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```
</p></details>

<details><summary>module-1/package.json</summary><p>

```json
{
  "name": "module-1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "module-0": "1.0.0"
  }
}
```
</p></details>

## file tree
```text
├── lerna.json
├── package.json
└── packages
    ├── module-0
    │   ├── index.js
    │   └── package.json
    ├── module-1
    │   ├── index.js
    │   └── package.json
    └── module-2
        ├── index.js
        └── package.json
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.4.1 |
| `node --version` | 8.12.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.1 |

**Comment by thenengah** [comment]
Also running into this issue. Currently having to run `lerna bootstrap`.

Here is the error i'm getting (`scope`, and `package` are obviously named differently):

`npm ERR! 404 Not Found: @scope/package@^0.0.0`

`node: 10.15.0, npm: 6.4.1, lerna: 3.13.1, mac: osx high sierra 10.13.6`

**Comment by luponZ** [comment]
> `node: 10.15.0, npm: 6.4.1, lerna: 3.13.1, mac: osx high sierra 10.13.6`
> 
> Also running into this issue. Currently having to run `lerna bootstrap`.
> 
> Here is the error i'm getting (`scope`, and `package` are obviously named differently):
> 
> `npm ERR! 404 Not Found: @scope/package@^0.0.0`
> 
> Looks like npm doesn't even try to look locally when installing.

**Comment by luponZ** [comment]
> `node: 10.15.0, npm: 6.4.1, lerna: 3.13.1, mac: osx high sierra 10.13.6`
> 
> Also running into this issue. Currently having to run `lerna bootstrap`.
> 
> Here is the error i'm getting (`scope`, and `package` are obviously named differently):
> 
> `npm ERR! 404 Not Found: @scope/package@^0.0.0`
> 
> Looks like npm doesn't even try to look locally when installing.

you can try this
```bash
lerna add module-1 packages/module-2
```
it work

**Comment by Christian24** [comment]
@luponZ I can confirm your solution works, however, I would like to know why. From my understanding it should also work with `--scope`. Maybe this should be reopened because it is a bug?

**Comment by artemjackson** [comment]
Still actual
@luponZ reopen pls

**Comment by evocateur** [comment]
Pretty sure this was broken in https://github.com/lerna/lerna/commit/71174e4709bb589fef2e9f835acb398a7918fdb0 and fixed in https://github.com/lerna/lerna/commit/9a5a29c862587c30ac78131b241b31782199f4f9 (published in v3.14.0)

**Comment by artemjackson** [comment]
@evocateur seems like the issue is still actual for v3.14.1
Tested via `lerna bootstrap --scope @my-scope/my-package`

**Comment by evocateur** [comment]
Yes, please note that this issue is _only_ occurring when you use `lerna add --scope <pkg>`. `lerna bootstrap --scope <pkg>` will still attempt to install local packages outside of that scope from the registry. It should be _extremely rare_ to explicitly use `--scope` with `lerna bootstrap`.

**Comment by cristiano-belloni** [comment]
This happens to me too.
```
lerna: 3.13.0
npm: 6.9.0
node: v10.16.1
OS: osx Mojave 10.14.6
```

**Comment by bgerd** [comment]
Just happened to me :/

The target's `package.json` gets updated, but the locally imported module does not get installed/linked into `node_modules`. 

Running `lerna bootstrap` after fixes everything 

```
lerna: 3.13.14
npm:  6.9.0
node: v10.16.1
```

**Comment by bgerd** [comment]
Scratch that. Missed @evocateur comment. Upgrading to `lerna@latest` currently at `v3.16.4` completely fixed the problem. Fyi. @cristiano-belloni

**Comment by cristiano-belloni** [comment]
@bgerd I had read that comment, but didn't read the last sentence :)
Thanks, I'll try that asap.

**Comment by hilleer** [comment]
I am sorry, but I still think this issue applies. Or at least something that seem related.. 

If I have a local dependency installed with a file path in a package `foo`: 

```
dependencies: {
    "bar": "file:../foo"
}
```

and I run `lerna bootstrap` it will **not** install bar in **node_modules** of **foo**.

If I do run `lerna bootstrap --scope foo` **it will?**

Is this intentionally or a hidden bug or are you just not supposed to be installing local dependencies like that?

**Comment by yanlee26** [comment]
same here
