### ISSUE TITLE
Issue in using workspace: protocol in lerna versioning / publish.

### ISSUE THREAD

**Issue by HariAbinesh** [lerna/lerna#3317]
Issue in using workspace: protocol in lerna versioning.

package A has two dependencies in workspace -> package B , C.

when we modify only package A  and trigger lerna version or publish, it fails.

## Current Behavior

lerna version / publish throws validation error.
To use the 'workspace:' protocol, ensure that a package with name "${depName}" exists in the current workspace.

## Expected Behavior

Lerna version / publish should succeed.

## Steps to Reproduce
package A has two dependencies in workspace -> package B , C

modify only package A and try versioning.

### Reason

First time, package graph will have all available workspace packages info in its Map.
But after lerna tries to write package json and CHANGELOG, the package graph will only have packages to publish info. so it fails.
```js
// File: package-graph/index.js line:60

 Object.keys(graphDependencies).forEach((depName) => {
        const depNode = this.get(depName);
// Here , the depNode will not be available.

```

### Environment

(lerna: 5.5.0 => 5.5.0)

**Comment by fahslaj** [comment]
Hi @HariAbinesh, thank you for opening this issue. I was able to successfully reproduce it and am currently working on a fix.

**Comment by JamesHenry** [comment]
@HariAbinesh this should be resolved in 5.5.1 thanks to @fahslaj

**Comment by forehalo** [comment]
unfortunately, #3322 did not solve this issue soundly, and I've met another issue related to this scenario.

Error says the following line in `@lerna/package-graph/index.js` didn't do nullish check(removed in #3322) before using it:
```js

const depNode = this.get(depName);
// L80 C37
const version = depNode.version;
```

I've created a repo to reproduce it: [lerna-version-issue](https://github.com/forehalo/lerna-version-issue/actions/runs/3058191161/jobs/4934123485)

**Comment by fox1t** [comment]
Same error here. I am not sure what should be the correct behavior, though. The version will be resolved later when the workspace protocol is used.

**Comment by joakimbeng** [comment]
I'm having the same issue as well!

**Comment by tehKapa** [comment]
On 5.6.1 the issue remains https://github.com/lerna/lerna/issues/3343
